# Generated by Django 5.1.4 on 2025-11-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_notification'),
        ('user', '0006_remove_orderitem_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.review'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('review', 'New Review'), ('order_cancelled', 'Order Cancelled'), ('low_stock', 'Low Stock')], default='order', max_length=20),
        ),
    ]
