# Generated by Django 5.1.4 on 2025-11-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_notification_review_and_more'),
        ('user', '0007_customernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_replies', to='user.review')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile')),
            ],
            options={
                'verbose_name_plural': 'Seller Replies',
            },
        ),
    ]
