# Generated by Django 5.1.4 on 2025-11-22 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_sellerreply'),
        ('user', '0007_customernotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerreply',
            options={'ordering': ['-replied_at'], 'verbose_name_plural': 'Seller Replies'},
        ),
        migrations.AlterField(
            model_name='sellerreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_replies', to='user.review'),
        ),
    ]
