# Generated by Django 5.2.8 on 2025-11-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('user', '0004_remove_review_comment_review_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='seller.sellerprofile'),
        ),
    ]
