# Generated by Django 5.2.8 on 2025-11-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_orderitem_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_seller',
        ),
    ]
